### ISSUE TITLE
On initial page load, filter is selected and when clearing filter by pressing on league, matches are empty

### ISSUE THREAD

**Issue by xilikas** [erikopinaldo/vlr-pro-tracker#24]
Clicking on "reset filter" shows all matches 
![Screenshot 2023-04-18 110755](https://user-images.githubusercontent.com/7342198/232821086-1c644cb1-dae3-4ec9-83f6-c5b4b7c02dc5.png)
![Screenshot 2023-04-18 110729](https://user-images.githubusercontent.com/7342198/232821088-7a708abc-2101-43da-bfc4-6f56eb7f4216.png)
![Screenshot 2023-04-18 110851](https://user-images.githubusercontent.com/7342198/232821091-2ca1c5ad-9e7e-4caf-861f-49f5f94fdfe6.png)

**Comment by erikopinaldo** [comment]
Looks to be an artifact of my hard-coded selected filters on page load, which are stored in state. Hard-coded filters are currently:

- "Champions Tour 2023: Pacific League"
- "Champions Tour 2023: Americas League"
- "Champions Tour 2023: EMEA League"

Sometimes, there won't be any upcoming matches for these filters, or there won't be matches for some of these filters. If no matches are found, nothing renders. 

On initial page load, if only one of these filters has matches and you unselect the filter, the filter is removed from state. However, the other 2 filters exist in state (without matches). As a result, no matches will be rendered until you change the filter selections. 

There is a more immediately apparent version of this bug wherein there are no matches for each filter on page load. This means that the initial page load will show a blank match table component. I will have to add a check for both of these scenarios.

**Comment by erikopinaldo** [comment]
Closed with above PR
